info:
  contact: {}
  description: 后台管理系统API接口文档
  title: 通用后台管理系统
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
